### ISSUE TITLE
close event should map to OpenFin closing event

### ISSUE THREAD

**Issue by bingenito** [Morgan-Stanley/desktopJS#238]
https://github.com/Morgan-Stanley/desktopJS/blob/1006640dadea8f05979bc76a2dfc0b422ec2f694/packages/desktopjs-openfin/src/openfin.ts#L20

**Comment by naknode** [comment]
Is this not what's happening?

**Comment by bingenito** [comment]
close-requested disables close unless you handle the callback.  It's mapped behind beforeunload across all containers in desktopJS.  The notification of a window closing should be mapped to closing.  This was a mismatched mapping from first iteration.
