### ISSUE TITLE
[Issue] README incomplete?

### ISSUE THREAD

**Issue by naknode** [Morgan-Stanley/desktopJS#242]
It seems the readme is not providing all sufficient details to start the desktopJS. For starts, `npm run server` no longer exists. I cannot seem to find it. Is this replaced by `npm run start`?

And when I install desktopJS and do `npm install`, and I go to`localhost:8000`, I get the following errors on Chrome:

```
GET http://localhost:8000/desktop.js net::ERR_ABORTED 404 (Not Found)
localhost/:10 GET http://localhost:8000/desktopjs-electron.js net::ERR_ABORTED 404 (Not Found)
localhost/:9 GET http://localhost:8000/desktopjs-openfin.js net::ERR_ABORTED 404 (Not Found)
localhost/:10 GET http://localhost:8000/desktopjs-electron.js net::ERR_ABORTED 404 (Not Found)
app.js:49 Uncaught ReferenceError: desktopJS is not defined
    at app.js:49
```

I am on MacOS Mojave if that makes a difference. (Doubt it.) Or maybe I'm misreading the documentation to get this up and running.

**Comment by naknode** [comment]
Got it. Thanks for the update. Was able to get it working.

**Comment by bingenito** [comment]
@naknode Thanks for taking the time to confirm the steps.  I'm updating the readme in #244
