### ISSUE TITLE
Renderer node integration disabled by default in electron 5

### ISSUE THREAD

**Issue by bingenito** [Morgan-Stanley/desktopJS#259]
Current workaround is to pass webPreferences: { nodeIntegration: true } on createWindow options

Should we add a "node" boolean as top level supported option to createWindow that gets properly mapped for each supporting container?  This can also be passed on options within resolveContainer and persisted by the container to be used implicitly on createWindow

**Comment by psmulovics** [comment]
You want to pass it over as part of the 4th parameter? Or as a 5th?

**Comment by bingenito** [comment]
A property on the optional options for both createWindow and resolveContainer.

**Comment by psmulovics** [comment]
That’s fair. Go for it.
