### ISSUE TITLE
Documentation links in the readme do not point to the correct URLS

### ISSUE THREAD

**Issue by Brookke** [Morgan-Stanley/desktopJS#305]
- `container` link 404s, should be https://morgan-stanley.github.io/desktopJS/classes/_desktopjs_src_container_.container.html
- `resolve` links to the wrong docs page and should be https://morgan-stanley.github.io/desktopJS/modules/_desktopjs_src_registry_.html#resolvecontainer I believe 

Correct me if I am wrong :)

**Comment by bingenito** [comment]
@Brookke Both look correct

**Comment by bingenito** [comment]
npmjs readme links will be updated on next release
