### ISSUE TITLE
Window height incorrectly saved/restored

### ISSUE THREAD

**Issue by Brookke** [Morgan-Stanley/desktopJS#310]
When saving and restoring the window layout, the child window gets taller and taller each time that the state is saved and restored.

## Steps taken:
1. Open a new window
2. Save layout
3. Restore layout

Repeat steps 2 and 3 and the window gets taller and taller. 

## GIF of the issue below 
![Screen Recording 2020-05-27 at 10 17 55 2020-05-27 10_23_54](https://user-images.githubusercontent.com/10200358/83001897-4370ca00-a004-11ea-8c6a-b7be91707372.gif)

## OS & Browser
I have tested the platforms below and confirmed that the issue is present on both.
- Windows 10, Chrome v81.0.4044.138
- macOS 10.15.4, Chrome v83.0.4103.61

**Comment by bingenito** [comment]
Still testing but it looks like if I change from outer to inner width and height in buildLayout it resolves this issue.  While testing I ran into many other edge cases dealing with non-primary monitor but I'll split those out as I'm not sure they are possible to fix for browser as it is more restrictive.

**Comment by Brookke** [comment]
That sounds similar to what I expected. I will give that a test locally and see how it goes.

As for the other issues I expect they are mostly browser limitations. There are a couple of proposals that may help in the future. See: https://github.com/webscreens/screen-enumeration and https://github.com/webscreens/window-placement

**Comment by Brookke** [comment]
@bingenito swapping to inner on build layout seems to fix the issue
