### ISSUE TITLE
Move from TSLint to ESLint

### ISSUE THREAD

**Issue by Brookke** [Morgan-Stanley/desktopJS#311]
Since tslint is now deprecated we should probably more the project over to ESLint

**Comment by Brookke** [comment]
Hey @bingenito, I am hoping to spend some time on this and #312 soon. Just wondering if you had any preference on the default ESLint rules? If not I am planning on using the airbnb ruleset.

**Comment by bingenito** [comment]
@Brookke No opinion (yet).  We can just review within the PR itself.
