### ISSUE TITLE
Test failures are not failing overall build

### ISSUE THREAD

**Issue by bingenito** [Morgan-Stanley/desktopJS#378]
Failures: 
1) DefaultMessageBus publish with non matching origin skips and continues
1.1) Expected spy postMessage to have been called 0 times. It was called 1 times.
343 specs, 1 failure, 2 pending specs
Finished in 0.8 seconds
The command "npm test" exited with 0.

**Comment by Brookke** [comment]
Related: https://github.com/sindresorhus/gulp-jasmine/issues/92
