### ISSUE TITLE
isSameOrigin seems to always return false

### ISSUE THREAD

**Issue by Brookke** [Morgan-Stanley/desktopJS#383]
https://github.com/Morgan-Stanley/desktopJS/blob/master/packages/desktopjs/src/Default/default.ts#L442

I believe that the window isn't resolved in time for it to get the correct location origin

This impacts window creation, meaning that windows are not stored when they are created in a browser, meaning things like layout saving fail to work

**Comment by bingenito** [comment]
Will probably remove the isSameOrigin check and go with per situation error handling to address cors issues
