### ISSUE TITLE
Typescript errors are ignored on `npm run build`

### ISSUE THREAD

**Issue by Brookke** [Morgan-Stanley/desktopJS#384]

**Comment by Brookke** [comment]
Based on the flakiness of gulp and the issues it has caused, I am tempted to consider just using plain npm scripts to replace gulp. Following a setup similar to this https://github.com/stereobooster/typescript-monorepo

**Comment by bingenito** [comment]
@Brookke I agree on dumping gulp.  In the interim do you have any time to test that pr branch yourself.  I tried with and without errors and it seemed good.

**Comment by Brookke** [comment]
@bingenito Will take a look tomorrow at that branch ☺️
